name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: npm
      - name: install npm
        run: npm i -g npm@latest
      - name: install npm packages
        run: npm ci
      - name: Run lint and formatter
        run: npm run check
